### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by esclapez** [AMReX-Combustion/PeleLMeX#15]
- [x] typical values (LE)
- [x] multi-component linear solves (LE)
- [x] MFbased interpolator (LE)
- [x] Fix level data layout (LE)
- [x] New MFI iterators
- [ ] extended CI
- [x] convergence testing: advection, diffusion, ADR (LE)
- [ ] regression tests
- [x] Hypre interface to linear solvers (LE)
- [x] turbulence inflow (LE)
- [x] hook to `dump_and_stop` available in AmrLevel
- [x] use TPROF on GPU to identify any issues, have scaling data (LE)
- [x] mass balance in closed chamber dp0dt (NW)
- [x] mixture fraction
- [x] control max level EB refinement (LE)
- [ ] control dt when adding level
- [x] cylindrical coordinates support
- [x] restore incompressible option
- [ ] Add option to prune covered boxes when EB
- [ ] Time averaged data

**Comment by esclapez** [comment]
TurbInflow in #31

**Comment by esclapez** [comment]
MFbased interpolator in #38

**Comment by esclapez** [comment]
Multi-component species diffusion in #39

**Comment by esclapez** [comment]
Level data layout in #40

**Comment by esclapez** [comment]
WeakScaling on PM after #40 
```
NodeCount  Efficiency          RunTime  Reaction  Diffusion  MacProj  NodalProj  ScalAdv  VelAdv  AvgDown  FillBoundary  ParallelCopy
0001       1.0                 178.9    123.9     31.69      5.127    2.192      2.723    5.099   6.269    9.774         28.94
0002       0.9410836401893741  190.1    129.4     36.09      4.496    2.329      3.098    5.52    7.411    10.99         40.17
0004       0.9141543178334186  195.7    130.3     39.05      4.911    2.596      3.224    6.096   7.771    12.58         44.26
0008       0.9053643724696356  197.6    130.4     40.19      5.054    2.63       3.292    6.263   7.76     13.19         46.34
0016       0.8980923694779117  199.2    130.5     40.94      5.473    2.765      3.324    6.573   7.895    13.65         48.59
0032       0.884330202669303   202.3    130.5     42.62      6.03     2.88       3.441    7.055   8.175    14.48         52.58
0064       0.867604267701261   206.2    130.6     44.4       6.935    3.028      3.509    7.745   8.527    15.44         55.67
0128       0.8454631379962193  211.6    130.5     47.24      7.894    3.072      3.651    8.9     9.277    17.81         61.59
0256       0.8191391941391941  218.4    131       50.52      9.351    3.255      3.91     9.628   9.932    18.69         73.06
0512       0.771786022433132   231.8    131       55.87      11.56    3.37       4.369    12.86   9.59     19.66         83.2
```

**Comment by esclapez** [comment]
Convergence testing in #46 and #50

**Comment by esclapez** [comment]
Incompressible runs in #56

**Comment by esclapez** [comment]
dump_and_stop hook in #59

**Comment by esclapez** [comment]
EB refinement in #52

**Comment by esclapez** [comment]
Closed chamber with mass injection in #66

**Comment by esclapez** [comment]
Mixture fraction in #76

**Comment by esclapez** [comment]
Closing this TODO list and opening, a new, updated one.
